[tool.poetry]
name = "llm-pentest"
version = "0.2.1"
description = "Pentesting POC using LLMs"
authors = ["Moritz Enderle <moritz.enderle@stud.th-deg.de>", 
           "Florian Eder <florian.eder3@stud.th-deg.de"]
readme = "README.md"
packages = [{include = "llm_pentest", from="src"}, {include = "chat", from="src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
jupyter = "^1.0.0"
openai = "^1.6.1"
langchain = "0.0.354"
langchain-openai = "^0.0.2"
paramiko = "^3.4.0"
langchainhub = "^0.1.14"
streamlit = "^1.29.0"
autogenstudio = "^0.0.25a0"
black = "^23.12.1"
isort = "^5.13.2"
chainlit = "0.7.700"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
