[tool.poetry]
name = "llm-pentest"
version = "0.1.0"
description = "Pentesting POC using LLMs"
authors = ["Moritz Enderle <moritz.enderle@stud.th-deg.de>"]
readme = "README.md"
packages = [{include = "llm_pentest"}]

[tool.poetry.dependencies]
python = "^3.10"
jupyter = "^1.0.0"
openai = "^1.6.1"
langchain = "^0.1.0"
langchain-openai = "^0.0.2"
paramiko = "^3.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
